service: api-microservices
provider:
  name: aws
  runtime: nodejs20.x
functions:
  marketing:
    handler: marketing/handler.main
  auth:
    handler: auth/handler.main
  orders:
    handler: orders/handler.main
  users:
    handler: users/handler.main
  products:
    handler: products/handler.main

plugins:
  - serverless-offline
